// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWSDEk9VXx7M5SUFSTzh8fkCke1_l4Nc',
    appId: '1:858609835323:web:a13dd971831f4f1648ab1e',
    messagingSenderId: '858609835323',
    projectId: 'project1-d01fb',
    authDomain: 'project1-d01fb.firebaseapp.com',
    storageBucket: 'project1-d01fb.appspot.com',
    measurementId: 'G-JN1HE24KQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-fK1esofH1HAl-rd4UJEf2zt9v3v-fDo',
    appId: '1:858609835323:android:3ab0e40650ddb4b248ab1e',
    messagingSenderId: '858609835323',
    projectId: 'project1-d01fb',
    storageBucket: 'project1-d01fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSUidl7eMG3mdLZ2NA0kaquf4ApWGbD84',
    appId: '1:858609835323:ios:8b2563bf505e228348ab1e',
    messagingSenderId: '858609835323',
    projectId: 'project1-d01fb',
    storageBucket: 'project1-d01fb.appspot.com',
    iosClientId: '858609835323-93tmni0pvdim2e15dkdbt2mvjujocdr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSUidl7eMG3mdLZ2NA0kaquf4ApWGbD84',
    appId: '1:858609835323:ios:8b2563bf505e228348ab1e',
    messagingSenderId: '858609835323',
    projectId: 'project1-d01fb',
    storageBucket: 'project1-d01fb.appspot.com',
    iosClientId: '858609835323-93tmni0pvdim2e15dkdbt2mvjujocdr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
